name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cat /etc/*release
        grep MH /proc/cpuinfo
        free -h
        curl https://inet-ip.info/ip
        npm i
        [[ ! -s node_modules/.bin/eslint ]] && npm ci
        npm run build --if-present
        npm test
        IMAGE=my-image-name:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE
        docker run --rm -i $IMAGE --help
        docker run --rm -i $IMAGE
      env:
        CI: true
